/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2018-02-15 21:38:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp_002dpropios;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.openxava.view.View;
import java.math.BigDecimal;
import java.sql.*;
import java.util.*;
import com.google.gson.*;
import fusioncharts.FusionCharts;
import org.openxava.*;

public final class barraDetalle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/openxava.tld", Long.valueOf(1518729816792L));
    _jspx_dependants.put("/jsp-propios/../xava/imports.jsp", Long.valueOf(1518729813978L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      org.openxava.controller.ModuleContext context = null;
      synchronized (session) {
        context = (org.openxava.controller.ModuleContext) _jspx_page_context.getAttribute("context", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (context == null){
          context = new org.openxava.controller.ModuleContext();
          _jspx_page_context.setAttribute("context", context, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');



String viewObject = request.getParameter("viewObject");
viewObject = (viewObject == null || viewObject.equals(""))?"xava_view":viewObject;
View view = (org.openxava.view.View) context.get(request,viewObject);

String hostdb = "localhost:3306";  // MySQl host
//String hostdb = "45.7.229.159:3306";
   String userdb = "mysql";  // MySQL username
   String passdb = "afrodita";  // MySQL password

   String namedb = "fateon";  // MySQL database name

    // Establish a connection to the database
    DriverManager.registerDriver(new com.mysql.jdbc.Driver());
    Connection con = DriverManager.getConnection("jdbc:mysql://" + hostdb + "/" + namedb , userdb , passdb);
         Gson gson = new Gson();
            
            // Form the SQL query that returns the top 10 most populous countries
           // String sqlQuery="SELECT * FROM fateon.fateon_registro where origen_id = '"+view.getValue("origen.oid")+"' GROUP BY registro_date_1";
            
            String sqlQuery = "SELECT * FROM fateon.fateon_registro where sensor_id= '"+view.getValue("sensor.oid")+"' and origen_id='"+view.getValue("origen.oid")+"' order by registro_date_1 asc limit 20";

            // Prepare the query statement    
            PreparedStatement pt=con.prepareStatement(sqlQuery);  
            // Prepare the query statement
            ResultSet rs=pt.executeQuery();
            
            // The 'chart' map object holds the chart attributes and data.
            Map<String, String> chart = new HashMap<String, String>();
            
            chart.put("caption", "Detalle por Dia Entrada Top 20");
            chart.put("paletteColors", "#0075c2");
            chart.put("bgColor", "#ffffff");
            chart.put("usePlotGradientColor", "0");
            chart.put("plotBorderAlpha", "10");
            chart.put("showXAxisLine", "1");
            chart.put("xAxisLineColor", "#999999");
            chart.put("showValues", "0");
            chart.put("divlineColor", "#999999");
            chart.put("divLineIsDashed", "1");
            chart.put("showAlternateHGridColor", "0");
            chart.put("showBorder", "0");
            chart.put("baseFont", "Helvetica Neue,Arial");
            chart.put("captionFontSize", "14");
            chart.put("drawCrossLine", "2");
    		chart.put("crossLineAlpha", "100");
    		chart.put("crossLineColor", "#cc3300");
    		chart.put("ajustDiv", "1");
    		//chart.put("yAxisMaxvalue", "10000000000");
    		chart.put("yAxisMinvalue", "10");
    		chart.put("numDivLines", "20");
    		//chart.put("numVDivLines", "200");
    		//chart.put("vDivLineColor", "#00ffaa");
    		//chart.put("VDivLineThickness", "10");//groso line vertical en px
    		chart.put("VDivLineAlpha", "50");//transparencia de la lineas verticales 0 trasparente 100 opaco
    		chart.put("showAlternateVGridColor", "1");
    		chart.put("alternateVGridColor", "#00ffaa");
    		//chart.put("alternateVGridAlpha", "50");
    		chart.put("drawAnchors", "1");
    		chart.put("crossLineColor", "#FAFAFA");
    		//chart.put("logoURL", "http://static.fusioncharts.com/sampledata/images/Logo-HM-72x72.png");
    		chart.put("logoScale", "110");
    		chart.put("logoPosition", "TR");
    		chart.put("logoAlpha", "40");
    		chart.put("exportenabled", "1");
    		chart.put("exportatclient", "1");
    		chart.put("exporthandler", "http://export.api3.fusioncharts.com");
    		chart.put("html5exporthandler", "http://export.api3.fusioncharts.com");
            // Push the data into the array using map object.
            ArrayList data = new ArrayList();
            
            /*
                `linkeddata` array: It contains data for individual linked 
                items. The links should be defined in the format 
                `newchart-dataformat-datasource`. 
            */
            ArrayList linkeddata = new ArrayList();
            while(rs.next()) {
                Map<String, String> lv = new HashMap<String, String>();
                lv.put("label", rs.getString("registro_date_1"));
                lv.put("value", rs.getString("registro_float_1"));
                lv.put("link", "newchart-json-" + rs.getString("registro_id"));
                data.add(lv);
      
                // Create the linkedDataObj for cities drilldown    
                Map<String, String> linkedDataObj = new HashMap<String, String>();
                // Inititate the linkedDataObj for cities drilldown
                linkedDataObj.put("id", rs.getString("registro_id"));
                
               // The 'linkedChartAttribute' map object holds the chart attributes .
                Map<String, String> linkedChartAttribute = new HashMap<String, String>();
                linkedChartAttribute.put("caption" , "Detalle Dia: " + rs.getString("registro_date_1") +"Top 25");
                linkedChartAttribute.put("paletteColors" , "#72D7B2");
                linkedChartAttribute.put("bgColor" , "#ffffff");
                linkedChartAttribute.put("borderAlpha", "20");
                linkedChartAttribute.put("canvasBorderAlpha", "0");
                linkedChartAttribute.put("usePlotGradientColor", "0");
                linkedChartAttribute.put("plotBorderAlpha", "10");
                linkedChartAttribute.put("showXAxisLine", "1");
                linkedChartAttribute.put("xAxisLineColor" , "#999999");
                linkedChartAttribute.put("showValues", "0");
                linkedChartAttribute.put("divlineColor" , "#999999");
                linkedChartAttribute.put("divLineIsDashed" , "1");
                linkedChartAttribute.put("showAlternateHGridColor" , "0");

                ArrayList linkedChartData = new ArrayList();
                
                //String sqlQueryDetail="SELECT registro_id, registro_time_1, registro_date_1, registro_float_1 from fateon.fateon_registro where origen_id ='"+view.getValue("origen.oid")+"' and registro_date_1 = ? ";
                String sqlQueryDetail="SELECT registro_id, registro_time_1, registro_date_1, registro_float_1 from fateon.fateon_registro where sensor_id= '"+view.getValue("sensor.oid")+"' and origen_id='"+view.getValue("origen.oid")+"' and registro_date_1 = ?  order by registro_date_1 asc limit 25";
                System.out.println(" JSP-->"+sqlQueryDetail);

                // Prepare the query statement.
                PreparedStatement ptDetail=con.prepareStatement(sqlQueryDetail);  
                ptDetail.setString(1, rs.getString("registro_date_1"));
                // Execute the query.
                ResultSet rsDetail=ptDetail.executeQuery();
                while(rsDetail.next()) {
                  Map<String, String> arrDara = new HashMap<String, String>();
                  arrDara.put("label", rsDetail.getString("registro_time_1"));
                  arrDara.put("value", rsDetail.getString("registro_float_1"));
                  linkedChartData.add(arrDara);
                } 
                
                //closing the connection.
                rsDetail.close();
            
            /*  create a 'linkedchart' map object to make a FC's 
                linkedchart structure.
            */    
                Map<String, String> linkedchart = new HashMap<String, String>();
            /*
                gson.toJson() the data to retrieve the string containing the
                JSON representation of the data in the array.
            */    
                linkedchart.put("chart", gson.toJson(linkedChartAttribute));
                linkedchart.put("data", gson.toJson(linkedChartData));
                
               
                linkedDataObj.put("linkedchart", gson.toJson(linkedchart));
                linkeddata.add(linkedDataObj);
            } //end of while loop
            
            //closing the connection.
            rs.close();
 
            
            
            /* Valores de referencia */
            
            
             /* Valores Flotante*/
            
         //sqlQuery = "SELECT (max(registro_float_1)*1.20) as lineatope FROM fateon.fateon_registro where origen_id ='"+view.getValue("origen.oid")+"'";
         sqlQuery ="SELECT (max(registro_float_1)*1.20) as lineatope FROM fateon.fateon_registro  where sensor_id='"+view.getValue("sensor.oid")+"' and origen_id='"+view.getValue("origen.oid")+"' order by registro_date_1";
		 pt=con.prepareStatement(sqlQuery);    
		 rs=pt.executeQuery();
		 rs.next();
		 String valorFlotabte= rs.getString("lineatope");
		 rs.close();
		 
		 
		 
		 /* Valores Percentil */
		  
		 sqlQuery = "SELECT (count(1)*95)/100 as total FROM fateon.fateon_registro  where sensor_id='"+view.getValue("sensor.oid")+"' and origen_id= '"+view.getValue("origen.oid")+"'";
		  
		 System.out.println(" JSP-->"+sqlQuery);
		 
		 pt=con.prepareStatement(sqlQuery);    
		 rs=pt.executeQuery();
		 rs.next();
		 int fila= rs.getInt("total");
		 rs.close();
		 
		 sqlQuery = "SELECT registro_float_1 as percentil FROM fateon.fateon_registro  where sensor_id='"+view.getValue("sensor.oid")+"' and origen_id= '"+view.getValue("origen.oid")+"' order by registro_float_1 asc limit "+fila+",1";
		  
		 System.out.println(" JSP-->"+sqlQuery);
		 
		 pt=con.prepareStatement(sqlQuery);    
		 rs=pt.executeQuery();
		 rs.next();
		 String percentil= rs.getString("percentil");
		 rs.close();
		
		 System.out.println("***************************************");
		 System.out.println("");
		 System.out.println(percentil);
		 System.out.println("");
		 System.out.println("***************************************");
		 
		 
            
            
            //create 'dataMap' map object to make a complete FC datasource.
            Map<String, String> dataMap = new LinkedHashMap<String, String>();  
        
            dataMap.put("chart", gson.toJson(chart));
            dataMap.put("data", gson.toJson(data));


    		Map<String, String> lineMap = new LinkedHashMap<String, String>();
    		ArrayList arrDataLine = new ArrayList();
    		ArrayList arrDataAllLine = new ArrayList();
    		Map<String, String> reg = new HashMap<String, String>();
    		reg.put("startvalue",valorFlotabte);
    		reg.put("displayvalue","TOPE CALCULADO: "+valorFlotabte);
    		reg.put("valueonright","1");
    		reg.put("color","#173B0B");
    		reg.put("origText","TOPE CALCULADO");
    		arrDataLine.add(0,reg);
    /*************/
    	Map<String, String> reg1 = new HashMap<String, String>();
    		reg1.put("startvalue",percentil);
    		reg1.put("displayvalue","PERCENTIL: "+percentil);
    		reg1.put("valueonright","1");
    		reg1.put("color","#FF3300");
    		reg1.put("origText","PERCENTIL");
    		arrDataLine.add(1,reg1);
    		lineMap.put("line", gson.toJson(arrDataLine));
    		arrDataAllLine.add(lineMap);
    		dataMap.put("trendlines", gson.toJson(arrDataAllLine));
    		
            dataMap.put("linkeddata", gson.toJson(linkeddata));
            
            

            FusionCharts columnChart= new FusionCharts(
                    "column2d",             //type of chart
                    "chart1",               //unique chart ID
                    "90%", "600", // chartWidth, chartHeight
                    "chart",                //div ID of the chart container
                    "json",                 //data format
                    gson.toJson(dataMap)    //data source
                );
           
            
      out.write("\r\n");
      out.write("            ");
      out.print(columnChart.render());
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\t<div id=\"chart\"></div>\r\n");
      out.write("\t<input type=\"button\" value=\"Actualizar Pagina\" onclick=\"window.location='/Afrodita/m/VerOrigen'\">\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
