

// File generated by OpenXava: Fri Oct 06 12:00:53 CEST 2017
// Archivo generado por OpenXava: Fri Oct 06 12:00:53 CEST 2017

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Month		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IMonth  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	public static final String PROPERTY_days = "days"; 
	int getDays() throws RemoteException;
	void setDays(int days) throws RemoteException; 	
	public static final String PROPERTY_name = "name"; 
	String getName() throws RemoteException;
	void setName(String name) throws RemoteException;		

	// References/Referencias

	// Methods 


}