/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2018-02-28 15:38:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xava;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.openxava.view.meta.MetaView;
import org.openxava.view.View;

public final class sections_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/xava/imports.jsp", Long.valueOf(1518728564560L));
    _jspx_dependants.put("/WEB-INF/openxava.tld", Long.valueOf(1518728567324L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005flink_0026_005fcssStyle_005fcssClass_005fargv_005faction;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fxava_005flink_0026_005fcssStyle_005fcssClass_005fargv_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fxava_005flink_0026_005fcssStyle_005fcssClass_005fargv_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.openxava.controller.ModuleContext context = null;
      synchronized (session) {
        context = (org.openxava.controller.ModuleContext) _jspx_page_context.getAttribute("context", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (context == null){
          context = new org.openxava.controller.ModuleContext();
          _jspx_page_context.setAttribute("context", context, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      org.openxava.web.style.Style style = null;
      style = (org.openxava.web.style.Style) _jspx_page_context.getAttribute("style", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (style == null){
        style = new org.openxava.web.style.Style();
        _jspx_page_context.setAttribute("style", style, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.openxava.web.layout.LayoutPainterManager layoutPainterManager = null;
      synchronized (session) {
        layoutPainterManager = (org.openxava.web.layout.LayoutPainterManager) _jspx_page_context.getAttribute("layoutPainterManager", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (layoutPainterManager == null){
          layoutPainterManager = new org.openxava.web.layout.LayoutPainterManager();
          _jspx_page_context.setAttribute("layoutPainterManager", layoutPainterManager, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      out.write('\n');

String viewObject = request.getParameter("viewObject");
viewObject = (viewObject == null || viewObject.equals(""))?"xava_view":viewObject;
org.openxava.view.View view = (org.openxava.view.View) context.get(request, viewObject);
java.util.Collection sections = view.getSections();
int activeSection = view.getActiveSection();

      out.write("\n");
      out.write("\n");
      out.write("<table width='100%' cellspacing=\"0\" border=\"0\" cellpadding=\"0\">\n");
      out.write("\t<tr><td>\n");
      out.write("\n");
      out.write("<div class=\"");
      out.print(style.getSection());
      out.write("\">\n");
      out.write("\t<table ");
      out.print(style.getSectionTableAttributes());
      out.write(">\n");
      out.write("    \t<tr>\n");
      out.write("    \t\t");
      out.print(style.getSectionBarStartDecoration());
      out.write("    \t\t\n");
      out.write("\t");
 
	java.util.Iterator itSections = sections.iterator();
	int i=0;
	while (itSections.hasNext()) {
		MetaView section = (MetaView) itSections.next();
		if (activeSection == i) {
	
      out.write("        \n");
      out.write("\t\t\t");
      out.print(style.getActiveSectionTabStartDecoration(i == 0, !itSections.hasNext()));
      out.write("\n");
      out.write("\t\t\t");
      out.print(section.getLabel(request));
      out.write("\n");
      out.write("\t\t\t");
      out.print(style.getActiveSectionTabEndDecoration());
      out.write("\n");
      out.write("    ");

		}
		else {
    
      out.write("\n");
      out.write("    \t\t");
      out.print(style.getSectionTabStartDecoration(i == 0, !itSections.hasNext()));
      out.write("\n");
      out.write("\t\t\t\t");

				String viewObjectArgv = "xava_view".equals(viewObject)?"":",viewObject=" + viewObject;
				
      out.write("\n");
      out.write("\t\t\t\t");
      //  xava:link
      org.openxava.web.taglib.LinkTag _jspx_th_xava_005flink_005f0 = (org.openxava.web.taglib.LinkTag) _005fjspx_005ftagPool_005fxava_005flink_0026_005fcssStyle_005fcssClass_005fargv_005faction.get(org.openxava.web.taglib.LinkTag.class);
      _jspx_th_xava_005flink_005f0.setPageContext(_jspx_page_context);
      _jspx_th_xava_005flink_005f0.setParent(null);
      // /xava/sections.jsp(43,4) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005flink_005f0.setAction("Sections.change");
      // /xava/sections.jsp(43,4) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005flink_005f0.setArgv("activeSection=" + i + viewObjectArgv);
      // /xava/sections.jsp(43,4) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005flink_005f0.setCssClass(style.getSectionLink());
      // /xava/sections.jsp(43,4) name = cssStyle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005flink_005f0.setCssStyle(style.getSectionLinkStyle());
      int _jspx_eval_xava_005flink_005f0 = _jspx_th_xava_005flink_005f0.doStartTag();
      if (_jspx_eval_xava_005flink_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          out.print(section.getLabel(request));
          out.write("\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_xava_005flink_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_xava_005flink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fxava_005flink_0026_005fcssStyle_005fcssClass_005fargv_005faction.reuse(_jspx_th_xava_005flink_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fxava_005flink_0026_005fcssStyle_005fcssClass_005fargv_005faction.reuse(_jspx_th_xava_005flink_005f0);
      out.write("      \n");
      out.write("\t\t\t");
      out.print(style.getSectionTabEndDecoration());
      out.write("\t\n");
      out.write("  \t");
   	
		}
		i++;
  	} 
  	
      out.write("                \n");
      out.write("  \t\t\t");
      out.print(style.getSectionBarEndDecoration());
      out.write("  \t\n");
      out.write("\t</tr>\n");
      out.write("  </table>\n");
      out.write("</div>      \n");
      out.write("\t\n");
      out.write("\t</td></tr>\n");
      out.write("\t\n");
      out.write("\t<tr><td class=\"");
      out.print(style.getActiveSection());
      out.write(' ');
      out.print(view.isFlowLayout()?"ox-flow-layout":"");
      out.write("\">\n");
      out.write("\t\t");

			String viewName = viewObject + "_section" + activeSection;
			context.put(request, viewName, view.getSectionView(activeSection));
		
      out.write("\t\t\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "detail.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("viewObject", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(viewName), request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("representsSection", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\t</td></tr>\t\n");
      out.write("</table>\n");
      out.write("<br>\n");

 // END IF Not painter is in use

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
