/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2018-04-14 01:43:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xava;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.openxava.web.WebEditors;
import org.openxava.view.View;
import org.openxava.tab.Tab;
import org.openxava.util.XavaPreferences;
import org.openxava.util.XavaResources;
import org.openxava.model.meta.MetaProperty;
import org.openxava.web.Ids;
import org.openxava.web.Collections;

public final class collectionFrameHeader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/xava/imports.jsp", Long.valueOf(1523283761000L));
    _jspx_dependants.put("/WEB-INF/openxava.tld", Long.valueOf(1523283762000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fxava_005fimage_0026_005fargv_005faction_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fxava_005fimage_0026_005fargv_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fxava_005fimage_0026_005fargv_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.openxava.controller.ModuleContext context = null;
      synchronized (session) {
        context = (org.openxava.controller.ModuleContext) _jspx_page_context.getAttribute("context", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (context == null){
          context = new org.openxava.controller.ModuleContext();
          _jspx_page_context.setAttribute("context", context, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      org.openxava.util.Messages errors = null;
      errors = (org.openxava.util.Messages) _jspx_page_context.getAttribute("errors", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (errors == null){
        errors = new org.openxava.util.Messages();
        _jspx_page_context.setAttribute("errors", errors, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\n');
      org.openxava.web.style.Style style = null;
      style = (org.openxava.web.style.Style) _jspx_page_context.getAttribute("style", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (style == null){
        style = new org.openxava.web.style.Style();
        _jspx_page_context.setAttribute("style", style, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String collectionName = request.getParameter("collectionName");
String viewObject = request.getParameter("viewObject");
View view = (View) context.get(request, viewObject);
View collectionView = view.getSubview(collectionName);
String viewName = viewObject + "_" + collectionName;
String frameId = Ids.decorate(request, "frame_" + view.getPropertyPrefix() + collectionName);
String hiddenStyle = view.isFrameClosed(frameId)?"":"style='display: none'";
if (!collectionView.isCollectionFromModel()) {
	Tab tab = collectionView.getCollectionTab();
	if (request.getAttribute(Tab.TAB_RESETED_PREFIX + tab) == null) {
		String collectionId = Collections.id(request, collectionName);
		String tabObject = Collections.tabObject(collectionId);
		tab.setTabObject(tabObject);		
		tab.setRequest(request);  
		tab.reset();
		request.setAttribute(Tab.TAB_RESETED_PREFIX + tab, Boolean.TRUE);
	}
}

      out.write("\n");
      out.write("<span ");
      out.print(hiddenStyle);
      out.write('>');
      out.write('\n');
      out.write('(');
      out.print(collectionView.getCollectionSize());
      out.write(')');
      out.write('\n');

	if (collectionView.isCollectionEditable()) {

      out.write('\n');
      //  xava:image
      org.openxava.web.taglib.ImageTag _jspx_th_xava_005fimage_005f0 = (org.openxava.web.taglib.ImageTag) _005fjspx_005ftagPool_005fxava_005fimage_0026_005fargv_005faction_005fnobody.get(org.openxava.web.taglib.ImageTag.class);
      _jspx_th_xava_005fimage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_xava_005fimage_005f0.setParent(null);
      // /xava/collectionFrameHeader.jsp(41,0) name = action type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fimage_005f0.setAction(collectionView.getNewCollectionElementAction());
      // /xava/collectionFrameHeader.jsp(41,0) name = argv type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_xava_005fimage_005f0.setArgv("viewObject="+viewName);
      int _jspx_eval_xava_005fimage_005f0 = _jspx_th_xava_005fimage_005f0.doStartTag();
      if (_jspx_th_xava_005fimage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fxava_005fimage_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005fimage_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fxava_005fimage_0026_005fargv_005faction_005fnobody.reuse(_jspx_th_xava_005fimage_005f0);
      out.write('\n');

	}

      out.write("\n");
      out.write("</span>\n");
      out.write("<span class=\"");
      out.print(style.getFrameTotals());
      out.write('"');
      out.write(' ');
      out.print(hiddenStyle);
      out.write('>');
      out.write('\n');

	int totalRows = collectionView.getCollectionTotalsCount();
int totalColumns = collectionView.getMetaPropertiesList().size();
for (int row=0; row<totalRows; row++) {	
	for (int column=0; column<totalColumns; column++) {
		if (collectionView.hasCollectionTotal(row, column)) {
	MetaProperty p = (MetaProperty) collectionView.getMetaPropertiesList().get(column);
	String ftotal = WebEditors.format(request, p, collectionView.getCollectionTotal(row, column), errors, view.getViewName(), true);

      out.write("\n");
      out.write("\t&nbsp;&nbsp;\t\t\t\t\n");
      out.write("\t<span class=\"");
      out.print(style.getFrameTotalsLabel());
      out.write('"');
      out.write('>');
      out.print(collectionView.getCollectionTotalLabel(row, column));
      out.write(":</span>\n");
      out.write("\t<span class=\"");
      out.print(style.getFrameTotalsValue());
      out.write('"');
      out.write('>');
      out.print(ftotal);
      out.write("</span>\n");

	}
	}
}

if (!collectionView.isCollectionFromModel() && XavaPreferences.getInstance().isSummationInList()) {
	Tab tab = collectionView.getCollectionTab();
	int totalTabColumns = tab.getMetaProperties().size();
	for (int column=0; column<totalTabColumns; column++) {
		if (!tab.isFixedTotal(column) && tab.hasTotal(column)) {
	MetaProperty p = tab.getMetaProperty(column);
	String ftotal = WebEditors.format(request, p, tab.getTotal(column), errors, view.getViewName(), true);
	String label = XavaResources.getString(request, "sum_of", p.getLabel());

      out.write("\n");
      out.write("\t&nbsp;&nbsp;\t\t\t\t\n");
      out.write("\t<span class=\"");
      out.print(style.getFrameTotalsLabel());
      out.write('"');
      out.write('>');
      out.print(label);
      out.write(":</span>\n");
      out.write("\t<span class=\"");
      out.print(style.getFrameTotalsValue());
      out.write('"');
      out.write('>');
      out.print(ftotal);
      out.write("</span>\n");
									
		}
	}
}

      out.write("\n");
      out.write("</span>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
